version: 0.2

phases:
  pre_build:
    commands:
      - echo logging into ecr
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building docker image
      - docker build -t $IMAGE_REPO_NAME:$MAJOR.$MINOR.$CODEBUILD_BUILD_NUMBER .
      - docker tag $IMAGE_REPO_NAME:$MAJOR.$MINOR.$CODEBUILD_BUILD_NUMBER $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$MAJOR.$MINOR.$CODEBUILD_BUILD_NUMBER

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing docker image
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$MAJOR.$MINOR.$CODEBUILD_BUILD_NUMBER